"""empty message

Revision ID: 20bc3bb35616
Revises: a3e2c50c61f9
Create Date: 2025-01-20 18:04:21.207126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bc3bb35616'
down_revision: Union[str, None] = 'a3e2c50c61f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit', sa.String(length=55), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unit')
    # ### end Alembic commands ###
