"""empty message

Revision ID: 62880b403c58
Revises: a1a6c214611c
Create Date: 2024-09-23 12:15:33.576050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62880b403c58'
down_revision: Union[str, None] = 'a1a6c214611c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('article', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'article')
    # ### end Alembic commands ###
