"""empty message

Revision ID: a1a6c214611c
Revises: 8189ebb32af2
Create Date: 2024-09-12 19:52:33.539144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a6c214611c'
down_revision: Union[str, None] = '8189ebb32af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('products', 'in_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('in_stock', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
